package dev.pia.movies.models;

import java.time.*;

import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.*;

@Document(collection = "reviews")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Review {

  // id are automatically generated by mongo, cannot pass an id to this class
  @Id
  private ObjectId id;

  private String body;

  private LocalDateTime dateCreated;

  private LocalDateTime timeCreated;

  //custom constructor that takes only the body
  public Review(String body, LocalDateTime dateCreated, LocalDateTime timeCreated) {
    this.body = body;
    this.dateCreated = dateCreated;
    this.timeCreated = timeCreated;
  }

  
}
